import {Quad as MyNode} from "Quad";
import {Cell} from "Cell";
export var canvasWidth;
export var canvasHeight;
export var qTree: MyNode = null;
export var nodeX = 0;
export var nodeY = 0;
export var nodesOnScreen = [];
export var playerCells :Cell[]= [];
export var nodes: { [key:number]:Cell; } = { };
export var nodelist: Cell[] = [];
export var cells: Cell[]= [];
export var timestamp = 0;
export var leftPos = 0;
export var topPos = 0;
export var rightPos = 1E4;
export var bottomPos = 1E4;
export var viewZoom = 1;
export var ua = false;
export var transparentRender = false;
